name: Release VSCode Extension

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送符合 semver 格式的标签时触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install -g @vscode/vsce
          pnpm install

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Publish Extension to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish --no-dependencies

      - name: List generated files
        run: ls -l

      - name: Rename VSIX file if needed
        run: |
          # Use pattern matching to find the VSIX file
          VSIX_FILE=$(ls quick-reference-*.vsix)
          echo "Found VSIX file: $VSIX_FILE"

          # Rename the file if the name does not match the expected version
          if [ "$VSIX_FILE" != "quick-reference-${{ env.VERSION }}.vsix" ]; then
            mv "$VSIX_FILE" "quick-reference-${{ env.VERSION }}.vsix"
          else
            echo "VSIX file already has the correct name."
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Extension Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./quick-reference-${{ env.VERSION }}.vsix
          asset_name: quick-reference-${{ env.VERSION }}.vsix
          asset_content_type: application/vsix
